[project]
name = "seabirdscientific"
version = "1.0.0-alpha"

authors = [
    {name = "Lukas Christensen", email = "lchristensen@seabird.com"},
    {name = "Jesse Templin", email = "jtemplin@seabird.com"},
]

description = "SeaBird Scientific Community Toolkit"
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
    "Private :: Do Not Upload",
]

dependencies = [
    "gsw==3.4.0",
    "matplotlib>=3.5.2",
    "notebook",
    "numpy>=1.22.3",
    "pandas>=1.4.2",
    "plotly>=5.7.0",
    "scipy>=1.8.1",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
