[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seabirdscientific"
version = "0.0.1"
authors = [
    {name = "Jesse Templin", email = "jtemplin@seabird.com"},
]
description = "SeaBird Scientific Community Toolkit"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "build==1.0.3",
    "autopep8==1.6.0",
    "gsw==3.4.0",
    "ipykernel==6.15.1",
    "matplotlib==3.5.2",
    "nbformat==5.3.0",
    "numpy==1.22.3",
    "pandas==1.4.2",
    "pytest==7.1.2",
    "plotly==5.7.0",
    "scipy==1.8.1",
]

[tool.setuptools]
py-modules = [
    "seabirdscientific"
]