[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seabirdscientific"
version = "0.0.1"
authors = [
    {name = "Jesse Templin", email = "jtemplin@seabird.com"},
]
description = "SeaBird Scientific Community Toolkit"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "notebook",
    "sbs-data-processing==0.2.4",
    "sbs-data-visualization==0.2.7"
]

[project.optional-dependencies]
dev = [
    "pytest"
]